// AUTO-GENERATED from w3c/csswg-drafts
// Commit: https://github.com/w3c/csswg-drafts/commit/bbb1d87033095f792421c668c4211bc4f00cfe93
// Do not edit this file directly.
#![allow(warnings)]
//! https://drafts.csswg.org/css-shaders-1/

mod impls;
use super::prelude::*;
use impls::*;
